[package]
name = "pwd-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.9"
rpassword = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"
sha2 = "0.9"
typenum = "1.12"
zeroize = "1.4"
